let CardInfo = [
    {
      "ID": 15308295,
      "Name": "Abyss Actor - Comic Relief",
      "Type": "Pendulum Effect Monster",
      "Description": "You can target 1 \"Abyss Actor\" Pendulum Monster you control and 1 monster your opponent controls; switch control of both monsters, then destroy this card. You can only use this effect of \"Abyss Actor - Comic Relief\" once per turn.\n",
      "type": "Abyss Actor",
      "image": "https://images.ygoprodeck.com/images/cards/15308295.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/15308295.jpg",
      "atk": 1000,
      "def": 2000,
      "level": 3,
      "10": "Fiend",
      "Element": "DARK"
    },
    {
      "ID": 41356845,
      "Name": "Acid Trap Hole",
      "Type": "Trap Card",
      "Description": "Target 1 face-down Defense Position monster on the field; flip it face-up, then destroy it if its DEF is 2000 or less, or return it face-down if its DEF is more than 2000.",
      "type": "Hole",
      "image": "https://images.ygoprodeck.com/images/cards/41356845.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/41356845.jpg",
      "atk": 1600,
      "def": 1900,
      "level": null,
      "10": "Normal",
      "Element": "WIND"
    },
    {
      "ID": 71620241,
      "Name": "Advanced Crystal Beast Sapphire Pegasus",
      "Type": "Effect Monster",
      "Description": "If \"Advanced Dark\" is not in the Field Zone, send this monster to the GY. If this card is Summoned: You can place 1 of your \"Advanced Crystal Beast\" monsters that is banished, in your hand, Deck, or GY face-up in your Spell & Trap Zone as a Continuous Spell. If this face-up card is destroyed in a Monster Zone, you can place it face-up in your Spell & Trap Zone as a Continuous Spell, instead of sending it to the GY.",
      "type": "Advanced Crystal Beast",
      "image": "https://images.ygoprodeck.com/images/cards/71620241.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/71620241.jpg",
      "atk": 1800,
      "def": 1200,
      "level": 4,
      "10": "Beast",
      "Element": "WIND"
    },
    {
      "ID": 28865322,
      "Name": "Aether, the Evil Empowering Dragon",
      "Type": "Pendulum Effect Monster",
      "Description": "\nOnce per turn: You can banish 1 \"Empowered Warrior\" monster from your Graveyard, then target 1 card on the field; destroy it.\n",
      "type": "Aether",
      "image": "https://images.ygoprodeck.com/images/cards/28865322.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/28865322.jpg",
      "atk": 2300,
      "def": 1600,
      "level": 6,
      "10": "Dragon",
      "Element": "DARK"
    },
    {
      "ID": 78121572,
      "Name": "Alchemist of Black Spells",
      "Type": "Effect Monster",
      "Description": "Once per turn, you can change this face-up Attack Position card you control to face-up Defense Position and place 1 Spell Counter on a face-up card you control that you can place a Spell Counter on.",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/78121572.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/78121572.jpg",
      "atk": 1200,
      "def": 1800,
      "level": 4,
      "10": "Spellcaster",
      "Element": "WIND"
    },
    {
      "ID": 42023223,
      "Name": "Alpha The Electromagnet Warrior",
      "Type": "Effect Monster",
      "Description": "If this card is Normal or Special Summoned: You can add 1 Level 8 \"Magna Warrior\" monster from your Deck to your hand. You can only use this effect of \"Alpha The Electromagnet Warrior\" once per turn. During your opponent's turn: You can Tribute this card; Special Summon 1 Level 4 \"Magnet Warrior\" monster from your Deck (this is a Quick Effect).",
      "type": "Magnet Warrior",
      "image": "https://images.ygoprodeck.com/images/cards/42023223.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/42023223.jpg",
      "atk": 1700,
      "def": 1100,
      "level": 3,
      "10": "Rock",
      "Element": "EARTH"
    },
    {
      "ID": 97182396,
      "Name": "Amaze Attraction Viking Vortex",
      "Type": "Trap Card",
      "Description": "Target 1 \"Amazement\" monster you control or 1 face-up monster your opponent controls; equip this card to it. You can activate the following effect, based on which player controls the equipped monster;\n",
      "type": "Attraction",
      "image": "https://images.ygoprodeck.com/images/cards/97182396.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/97182396.jpg",
      "atk": 1200,
      "def": 220,
      "level": null,
      "10": "Normal",
      "Element": "WIND"
    },
    {
      "ID": 50669347,
      "Name": "Nephthys, the Sacred Preserver",
      "Type": "Link Monster",
      "Description": "2 \"Nephthys\" monsters\nYou can only use the following effect of \"Nephthys, the Sacred Preserver\" once per turn. During your Main Phase, if this card was Link Summoned: You can activate 1 of these effects;\n",
      "type": "Nephthys",
      "image": "https://images.ygoprodeck.com/images/cards/50669347.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/50669347.jpg",
      "atk": 1200,
      "def": 220,
      "level": null,
      "10": "Winged Beast",
      "Element": "FIRE"
    },
    {
      "ID": 80896940,
      "Name": "Nirvana High Paladin",
      "Type": "Synchro Pendulum Effect Monster",
      "Description": "\n1 Tuner + 1 or more non-Tuner Synchro Monsters\nFor this card's Synchro Summon, you can treat 1 Pendulum Summoned Pendulum Monster you control as a Tuner. If this card is Synchro Summoned using a Pendulum Summoned Pendulum Monster Tuner: You can target 1 card in your Graveyard; add it to your hand. When this card destroys an opponent's monster by battle: You can halve your opponent's LP. If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone.",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/80896940.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/80896940.jpg",
      "atk": 3300,
      "def": 2500,
      "level": 10,
      "10": "Spellcaster",
      "Element": "DARK"
    },
    {
      "ID": 14878871,
      "Name": "Rescue Cat",
      "Type": "Effect Monster",
      "Description": "You can send this card to the GY; Special Summon 2 Level 3 or lower Beast monsters from your Deck, but their effects are negated, also they are destroyed during the End Phase. You can only use this effect of \"Rescue Cat\" once per turn.",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/14878871.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/14878871.jpg",
      "atk": 300,
      "def": 100,
      "level": 4,
      "10": "Beast",
      "Element": "EARTH"
    },
    {
      "ID": 44203504,
      "Name": "Robotic Knight",
      "Type": "Normal Monster",
      "Description": "The Commander of Machine-Types, he serves the Machine King. He is famous for the way he controls his troops.",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/44203504.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/44203504.jpg",
      "atk": 1600,
      "def": 1800,
      "level": 4,
      "10": "Machine",
      "Element": "FIRE"
    },
    {
      "ID": 93104633,
      "Name": "Security Token",
      "Type": "Token",
      "Description": "This card can be used as a \"Security Token\".\n\n",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/93104633.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/93104633.jpg",
      "atk": 2000,
      "def": 2000,
      "level": 4,
      "10": "Cyberse",
      "Element": "LIGHT"
    },
    {
      "ID": 99899504,
      "Name": "Skull Flame",
      "Type": "Effect Monster",
      "Description": "Once per turn, you can Special Summon 1 \"Burning Skull Head\" from your hand. You cannot conduct your Battle Phase the turn you activate this effect. You can add 1 \"Burning Skull Head\" from your Graveyard to your hand instead of conducting a normal draw in your Draw Phase.",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/99899504.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/99899504.jpg",
      "atk": 2600,
      "def": 2000,
      "level": 8,
      "10": "Zombie",
      "Element": "FIRE"
    },
    {
      "ID": 15734813,
      "Name": "Soul Tiger",
      "Type": "Normal Monster",
      "Description": "The soul of a tiger that is said to devour human souls. He is a famous soul that you wouldn't want to run into in a dark alley.",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/15734813.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/15734813.jpg",
      "atk": 600,
      "def": 2100,
      "level": 4,
      "10": "Beast",
      "Element": "EARTH"
    },
    {
      "ID": 70668285,
      "Name": "Star Seraph Sword",
      "Type": "Effect Monster",
      "Description": "Once per turn: You can send 1 \"Star Seraph\" monster from your hand to the Graveyard; this card gains ATK equal to the original ATK of the sent monster, until the End Phase.",
      "type": "Star Seraph",
      "image": "https://images.ygoprodeck.com/images/cards/70668285.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/70668285.jpg",
      "atk": 1400,
      "def": 1000,
      "level": 4,
      "10": "Fairy",
      "Element": "LIGHT"
    },
    {
      "ID": 75988594,
      "Name": "Superheavy Samurai Swordmaster Musashi",
      "Type": "Synchro Monster",
      "Description": "1 Tuner + 1+ non-Tuner monsters\nWhen this card is Synchro Summoned: You can target 1 Machine monster in your GY; add it to your hand, also if you have a Spell/Trap in your GY, you cannot Normal or Special Summon it, or a monster with its name, for the rest of this turn. This card can attack while in face-up Defense Position. If it does, apply its DEF for damage calculation.",
      "type": "Superheavy",
      "image": "https://images.ygoprodeck.com/images/cards/75988594.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/75988594.jpg",
      "atk": 300,
      "def": 2300,
      "level": 5,
      "10": "Machine",
      "Element": "EARTH"
    },
    {
      "ID": 5399521,
      "Name": "Symphonic Warrior Miccs",
      "Type": "Pendulum Effect Monster",
      "Description": "\nUnless you have a \"Symphonic Warrior\" card in your other Pendulum Zone, this card's Pendulum Scale becomes 4. Once per turn, during your End Phase: You can target 1 of your banished \"Symphonic Warrior\" monsters; add it to your hand.\n",
      "type": "Symphonic Warrior",
      "image": "https://images.ygoprodeck.com/images/cards/5399521.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/5399521.jpg",
      "atk": 2300,
      "def": 1100,
      "level": 5,
      "10": "Machine",
      "Element": "WIND"
    },
    {
      "ID": 60715406,
      "Name": "Tentacle Plant",
      "Type": "Normal Monster",
      "Description": "A carnivorous plant that has an outgrowth of tentacles. It attacks someone nearby by extending its tentacles.",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/60715406.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/60715406.jpg",
      "atk": 500,
      "def": 600,
      "level": 2,
      "10": "Plant",
      "Element": "WATER"
    },
    {
      "ID": 38529357,
      "Name": "The Agent of Life - Neptune",
      "Type": "Effect Monster",
      "Description": "You can discard this card; Special Summon 1 \"The Agent\" monster from your hand or GY, except \"The Agent of Life - Neptune\", but it cannot be Tributed until the end of your opponent's turn. If \"The Sanctuary in the Sky\" is on the field or in the GY, you can Special Summon 1 \"Hyperion\" monster instead. If this card is banished: You can add 1 \"The Sanctuary in the Sky\" from your Deck to your hand. You can only use each effect of \"The Agent of Life - Neptune\" once per turn.",
      "type": "The Agent",
      "image": "https://images.ygoprodeck.com/images/cards/38529357.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/38529357.jpg",
      "atk": 900,
      "def": 600,
      "level": 1,
      "10": "Fairy",
      "Element": "LIGHT"
    },
    {
      "ID": 90488465,
      "Name": "The Chaos Creator",
      "Type": "Effect Monster",
      "Description": "Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your GY. If you control this card that was Special Summoned from the hand: You can target 3 banished monsters with different names; Special Summon 1 of them, then place the rest on the bottom of the Deck in any order. You can only use this effect of \"The Chaos Creator\" once per turn.",
      "type": "Chaos",
      "image": "https://images.ygoprodeck.com/images/cards/90488465.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/90488465.jpg",
      "atk": 2300,
      "def": 3000,
      "level": 8,
      "10": "Thunder",
      "Element": "DARK"
    },
    {
      "ID": 65403020,
      "Name": "The End of Anubis",
      "Type": "Effect Monster",
      "Description": "While this card is face-up on the field, all effects of Spell, Trap, and Monster Cards that target a card(s) in the Graveyard or that activate in the Graveyard are negated.",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/65403020.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/65403020.jpg",
      "atk": 2500,
      "def": 800,
      "level": 6,
      "10": "Fiend",
      "Element": "DARK"
    },
    {
      "ID": 27618634,
      "Name": "The Unhappy Girl",
      "Type": "Effect Monster",
      "Description": "While this card is in face-up Attack Position on the field, this card is not destroyed as a result of battle. (Damage calculation is applied normally.) A monster that battled with this card cannot change its battle position, except with a card effect, or attack while this card is in face-up Attack Position on the field.",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/27618634.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/27618634.jpg",
      "atk": 400,
      "def": 300,
      "level": 2,
      "10": "Spellcaster",
      "Element": "LIGHT"
    },
    {
      "ID": 68860936,
      "Name": "Tindangle Angel",
      "Type": "Flip Effect Monster",
      "Description": "FLIP: You can Special Summon 1 Flip monster from your hand or GY in face-down Defense Position, except \"Tindangle Angel\", then, if it is your opponent's Battle Phase, end the Battle Phase. You can only use this effect of \"Tindangle Angel\" once per turn.",
      "type": "Tindangle",
      "image": "https://images.ygoprodeck.com/images/cards/68860936.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/68860936.jpg",
      "atk": 500,
      "def": 1800,
      "level": 4,
      "10": "Fiend",
      "Element": "DARK"
    },
    {
      "ID": 12538374,
      "Name": "Treeborn Frog",
      "Type": "Effect Monster",
      "Description": "Once per turn, during your Standby Phase, if this card is in your Graveyard and you do not control \"Treeborn Frog\": You can Special Summon this card. You must control no Spell/Trap Cards to activate and to resolve this effect.",
      "type": "Frog",
      "image": "https://images.ygoprodeck.com/images/cards/12538374.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/12538374.jpg",
      "atk": 100,
      "def": 100,
      "level": 1,
      "10": "Aqua",
      "Element": "WATER"
    },
    {
      "ID": 60806437,
      "Name": "UFO Turtle",
      "Type": "Effect Monster",
      "Description": "When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 FIRE monster with 1500 or less ATK from your Deck, in face-up Attack Position.",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/60806437.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/60806437.jpg",
      "atk": 1400,
      "def": 1200,
      "level": 4,
      "10": "Machine",
      "Element": "FIRE"
    },
    {
      "ID": 56387350,
      "Name": "Vampire Baby",
      "Type": "Effect Monster",
      "Description": "At the end of the Battle Phase, if this card destroyed a monster by battle and sent it to the Graveyard this turn: You can Special Summon that monster to your side of the field.",
      "type": "Vampire",
      "image": "https://images.ygoprodeck.com/images/cards/56387350.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/56387350.jpg",
      "atk": 700,
      "def": 1000,
      "level": 3,
      "10": "Zombie",
      "Element": "DARK"
    },
    {
      "ID": 33112041,
      "Name": "Volcanic Rat",
      "Type": "Normal Monster",
      "Description": "This mutated mouse dwells in the core of active volcanoes. No amount of heat is too much for it to bear.",
      "type": "Volcanic",
      "image": "https://images.ygoprodeck.com/images/cards/33112041.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/33112041.jpg",
      "atk": 500,
      "def": 500,
      "level": 1,
      "10": "Pyro",
      "Element": "FIRE"
    },
    {
      "ID": 5614808,
      "Name": "White Aura Whale",
      "Type": "Synchro Monster",
      "Description": "1 WATER Tuner + 1+ non-Tuner WATER monsters\nWhen this card is Synchro Summoned: You can destroy all your opponent's Attack Position monsters. This card can make up to 2 attacks on monsters during each Battle Phase. If this card attacks a Defense Position monster, inflict piercing battle damage. If this card you control is destroyed by an opponent's card (by battle or card effect) and sent to your GY: You can banish 1 other WATER monster from your GY; Special Summon this card, and if you do, it is treated as a Tuner.",
      "type": "White",
      "image": "https://images.ygoprodeck.com/images/cards/5614808.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/5614808.jpg",
      "atk": 2800,
      "def": 2000,
      "level": 8,
      "10": "Fish",
      "Element": "WATER"
    },
    {
      "ID": 17511156,
      "Name": "Wood Clown",
      "Type": "Normal Monster",
      "Description": "A creature with a wicked smile and a lethal sickle.",
      "type": "",
      "image": "https://images.ygoprodeck.com/images/cards/17511156.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/17511156.jpg",
      "atk": 800,
      "def": 1200,
      "level": 3,
      "10": "Warrior",
      "Element": "EARTH"
    },
    {
      "ID": 81254059,
      "Name": "Worm Queen",
      "Type": "Effect Monster",
      "Description": "You can Tribute Summon this card in face-up Attack Position by Tributing 1 Reptile-Type \"Worm\" monster. Once per turn, you can Tribute 1 Reptile-Type \"Worm\" monster to Special Summon 1 Reptile-Type \"Worm\" monster from your Deck with a Level less than or equal to the Tributed monster.",
      "type": "Worm",
      "image": "https://images.ygoprodeck.com/images/cards/81254059.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/81254059.jpg",
      "atk": 2700,
      "def": 1100,
      "level": 8,
      "10": "Reptile",
      "Element": "LIGHT"
    },
    {
      "ID": 14970113,
      "Name": "Zoodiac Hammerkong",
      "Type": "XYZ Monster",
      "Description": "3 or more Level 4 monsters\nOnce per turn, you can also Xyz Summon \"Zoodiac Hammerkong\" by using 1 \"Zoodiac\" monster you control with a different name as Xyz Material. (If you used an Xyz Monster, any Xyz Materials attached to it also become Xyz Materials on this card.) This card gains ATK and DEF equal to the ATK and DEF of all \"Zoodiac\" monsters attached to it as Materials. While this card has Xyz Material, your opponent cannot target face-up \"Zoodiac\" monsters on the field with card effects, except this one. Once per turn, during the End Phase: Detach 1 Xyz Material from this card.",
      "type": "Zoodiac",
      "image": "https://images.ygoprodeck.com/images/cards/14970113.jpg",
      "image_small": "https://images.ygoprodeck.com/images/cards_small/14970113.jpg",
      "atk": 1000,
      "def": 3000,
      "level": 4,
      "10": "Beast-Warrior",
      "Element": "EARTH"
    }
   ]

export const getCardInfoById = ( cardId ) => {

    // "https://raw.githubusercontent.com/ermsharo/reference-images-repo/main/references-yu/DalleMiniById/12538374/this.png"

    for (let i = 0; i < CardInfo.length; i++) {
        if (CardInfo[i].ID == cardId) {
            return {
                "ID": CardInfo[i].ID,
                "Name": CardInfo[i].Name,
                "Type": CardInfo[i].Type,
                "Description": CardInfo[i].Description,
                "type": CardInfo[i].type,
                "image": `https://raw.githubusercontent.com/ermsharo/reference-images-repo/main/references-yu/DalleMiniById/${cardId}/this.png`,
                "image_small": CardInfo[i].image_small,
                "atk": CardInfo[i].atk,
                "def": CardInfo[i].def,
                "level": CardInfo[i].level,
                "10": CardInfo[i]["10"],
                "Element": CardInfo[i].Element
            }
        }
    }
}


export const getListOfIds = () => {

    // "https://raw.githubusercontent.com/ermsharo/reference-images-repo/main/references-yu/DalleMiniById/12538374/this.png"

    let cardIds = []; 
    for (let i = 0; i < CardInfo.length; i++) {
       cardIds.push(CardInfo[i].ID)
    }

    return cardIds; 
}